[package]
name = "backend-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = "1.0.219"
serde_json = "1.0.140"
sqlx = "0.8.6"
tokio = { version = "1.45.1", features = ["full"] }
